### ISSUE TITLE
Direct connect misleading statement on self service installation

### ISSUE THREAD

**Issue by wolruf** [awsdocs/aws-direct-connect-user-guide#10]
Hello, documentation leaves room for interpretation when it states:
"Connect directly to an AWS device from your router at an AWS Direct Connect location"
it feels like customer can connect himself directly.

https://docs.aws.amazon.com/directconnect/latest/UserGuide/getting_started.html

**Comment by browndjaz** [comment]
Hi,

Thanks for the comment. I have updated the page.

https://docs.aws.amazon.com/directconnect/latest/UserGuide/getting_started.html
