### ISSUE TITLE
Minor missing blank space

### ISSUE THREAD

**Issue by wolruf** [awsdocs/aws-direct-connect-user-guide#23]
Hello,
URI:
https://docs.aws.amazon.com/directconnect/latest/UserGuide/routing-and-bgp.html
doesn't have same content on Github so opening an issue instead.

There's a missing blank space at "If the Direct Connect Location 1 home AWS Region is the same as the VPC home Region, we use Direct Connect Location 1 over Direct Connect Location 2because we prefer local Region homed PoPs over inter-Region PoPs."

at "Location 2because" should read:
"If the Direct Connect Location 1 home AWS Region is the same as the VPC home Region, we use Direct Connect Location 1 over Direct Connect Location 2 because we prefer local Region homed PoPs over inter-Region PoPs."

**Comment by browndjaz** [comment]
Hi,

Thanks for the feedback. This has been fixed.
