### ISSUE TITLE
Documenation in this repository out of sync with the website

### ISSUE THREAD

**Issue by elliotsegler** [awsdocs/aws-direct-connect-user-guide#64]
It looks like the documentation in this repository is not in-sync with the public documentary on the website.

Example: 

https://github.com/awsdocs/aws-direct-connect-user-guide/blob/master/doc_source/direct-connect-gateways-intro.md
and
https://docs.aws.amazon.com/directconnect/latest/UserGuide/direct-connect-gateways-intro.html

Docs site currently has more information about VPC to VPC traffic and supernets.

Can someone please look into the sync here?

**Comment by julieso** [comment]
Thanks for letting us know. I've refreshed the repository.
