### ISSUE TITLE
Direct Connect locations for AWS GovCloud (US-East)?

### ISSUE THREAD

**Issue by pkazmier** [awsdocs/aws-direct-connect-user-guide#8]
[`Colocation.md`](https://github.com/awsdocs/aws-direct-connect-user-guide/blob/master/doc_source/Colocation.md) does not list the Direct Connect locations for GovCloud in US-East. I also cannot find it on the product page either: https://aws.amazon.com/directconnect/partners/

**Comment by browndjaz** [comment]
Hi,

I have added a section on the page that explains that you can't order connections for the location.

Thanks
