### ISSUE TITLE
Multi Account DX Gateway requirements

### ISSUE THREAD

**Issue by wolruf** [awsdocs/aws-direct-connect-user-guide#9]
Hello, I had customers asking if they needed to recreate their DXG to take advantage of multi accounts. Might be worth documenting they can keep their existing setup with an existing DXG.
https://docs.aws.amazon.com/directconnect/latest/UserGuide/multi-account-associate-vgw.html

**Comment by browndjaz** [comment]
Hi,

I've added the information in.

https://docs.aws.amazon.com/directconnect/latest/UserGuide/multi-account-associate-vgw.html

Thank you for the feedback.
